### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by jhourlad** [BootstrapDash/Material-Admin#1]
```npm install``` causes error due to outdated package:

```
Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-59_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-59_binding.node": 

HTTP error 404 Not Found

```

**Comment by BlackVikingPro** [comment]
See [Pull Request #5](https://github.com/BootstrapDash/Material-Admin/pull/5) to fix this.

**Comment by bootstrapdash-team** [comment]
We have updated the template to a newer version with design improvements and bug fixes. We have updated the version of mdc framework as well. Please check and feel free to reopen this thread if the issue still occurs.
