### ISSUE TITLE
Sidebar Expending Issue

### ISSUE THREAD

**Issue by saaiful** [BootstrapDash/Material-Admin#2]
If I have many items in the sidebar, it expands to a fixed point. Casing point: 
1. go to http://www.bootstrapdash.com/demo/material-admin/jquery/index.html
2. Click "UI Features"
3. Click "Charts" 
And you will see.

**Comment by bootstrapdash-team** [comment]
Hi @saaiful ,
We have updated the template to a newer version with design improvements and bug fixes. We have updated the version of mdc framework as well. Please check.

**Comment by bootstrapdash-team** [comment]
Please feel free to reopen this thread of the issue still occurs in the newer version
