### ISSUE TITLE
Side menu issue

### ISSUE THREAD

**Issue by younsahamed** [BootstrapDash/Material-Admin#4]
Click "sample pages" in side menu.
Can not able to see all sub menu if its beyond screen

**Comment by bootstrapdash-team** [comment]
Hi @younsahamed, We have updated the template to a newer version with design improvements and bug fixes. We have updated the version of mdc framework as well. Please check.

**Comment by bootstrapdash-team** [comment]
Please feel free to reopen this thread of the issue still occurs in the newer version
