### ISSUE TITLE
menu has bug

### ISSUE THREAD

**Issue by reza3zar** [BootstrapDash/Material-Admin#6]
hi,
you use material web component and it has a significant problem in toggle menu Item.
var menu = new mdc.menu.MDCSimpleMenu(menuEl); in matrial.js
this code, not support

**Comment by bootstrapdash-team** [comment]
Hi @reza3zar We have updated the template to a newer version with design improvements and bug fixes. We have updated the version of mdc framework as well. Please check.

**Comment by bootstrapdash-team** [comment]
Please feel free to reopen this thread of the issue still occurs in the newer version
